/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerRunner */

#ifndef _Included_ServerRunner
#define _Included_ServerRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ServerRunner
 * Method:    mainCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ServerRunner_mainCall
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    printGraph
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_printGraph
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    PrintFriendList
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_PrintFriendList
  (JNIEnv *, jclass, jint);

/*
 * Class:     ServerRunner
 * Method:    PrintMutualFriends
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_PrintMutualFriends
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ServerRunner
 * Method:    LoadProfile
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_LoadProfile
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ServerRunner
 * Method:    SearchAnyUser
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_SearchAnyUser
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    breadthFirst
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_breadthFirst
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    UpdateCollegeDetails
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_UpdateCollegeDetails
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    UpdateCityDetails
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_UpdateCityDetails
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    UpdatePassword
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_UpdatePassword
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    updateProfilePic
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ServerRunner_updateProfilePic
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    AcceptRejectRequest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ServerRunner_AcceptRejectRequest
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ServerRunner
 * Method:    SendFriendRequest
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ServerRunner_SendFriendRequest
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ServerRunner
 * Method:    SendNotification
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_SendNotification
  (JNIEnv *, jclass, jint);

/*
 * Class:     ServerRunner
 * Method:    GetAllMessages
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_GetAllMessages
  (JNIEnv *, jclass, jint);

/*
 * Class:     ServerRunner
 * Method:    SendMessageToUser
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_SendMessageToUser
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    AuthenticateUser
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_AuthenticateUser
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ServerRunner
 * Method:    AddVertex
 * Signature: (Ljava/lang/String;ILjava/lang/String;ICLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ServerRunner_AddVertex
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jchar, jstring, jstring);

/*
 * Class:     ServerRunner
 * Method:    DeleteVertex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ServerRunner_DeleteVertex
  (JNIEnv *, jclass, jint);

/*
 * Class:     ServerRunner
 * Method:    getNoOfVertices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ServerRunner_getNoOfVertices
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    getEdges
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_ServerRunner_getEdges
  (JNIEnv *, jclass, jint);

/*
 * Class:     ServerRunner
 * Method:    SaveUsersToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ServerRunner_SaveUsersToFile
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    SaveLinksToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ServerRunner_SaveLinksToFile
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    WriteMessagesToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ServerRunner_WriteMessagesToFile
  (JNIEnv *, jclass);

/*
 * Class:     ServerRunner
 * Method:    SavePendingStatusesToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ServerRunner_SavePendingStatusesToFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
