/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_SocioNet_ServerRunner */

#ifndef _Included_org_SocioNet_ServerRunner
#define _Included_org_SocioNet_ServerRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    mainCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_mainCall
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    printGraph
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_printGraph
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    PrintFriendList
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_PrintFriendList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    PrintMutualFriends
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_PrintMutualFriends
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    LoadProfile
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_LoadProfile
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SearchAnyUser
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_SearchAnyUser
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    breadthFirst
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_breadthFirst
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    UpdateCollegeDetails
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_UpdateCollegeDetails
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    UpdateCityDetails
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_UpdateCityDetails
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    UpdatePassword
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_UpdatePassword
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    updateProfilePic
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_updateProfilePic
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    UpdateStatus
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_UpdateStatus
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    AcceptRejectRequest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_SocioNet_ServerRunner_AcceptRejectRequest
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SendFriendRequest
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_SendFriendRequest
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SendNotification
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_SendNotification
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    GetAllMessages
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_GetAllMessages
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SendMessageToUser
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_SendMessageToUser
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    AuthenticateUser
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_AuthenticateUser
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    AddVertex
 * Signature: (Ljava/lang/String;ILjava/lang/String;ICLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_AddVertex
  (JNIEnv *, jclass, jstring, jint, jstring, jint, jchar, jstring, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    DeleteVertex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_DeleteVertex
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getNoOfVertices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_SocioNet_ServerRunner_getNoOfVertices
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getEdges
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_SocioNet_ServerRunner_getEdges
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    createNewGroup
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_createNewGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    addMemberToGroup
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_addMemberToGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getAllMembersOfGroup
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_getAllMembersOfGroup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    postToGroup
 * Signature: (IILjava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_postToGroup
  (JNIEnv *, jclass, jint, jint, jstring, jlong);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getAllPosts
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_getAllPosts
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getGroupInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_getGroupInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    searchWithinTheGroup
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_searchWithinTheGroup
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    searchForGroup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_searchForGroup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    getPerPersonGroupList
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_getPerPersonGroupList
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    generateNewsFeed
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_generateNewsFeed
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    acceptOrRejectGroupRequest
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_SocioNet_ServerRunner_acceptOrRejectGroupRequest
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SaveUsersToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_SaveUsersToFile
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SaveLinksToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_SaveLinksToFile
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    WriteMessagesToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_WriteMessagesToFile
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    SavePendingStatusesToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_SavePendingStatusesToFile
  (JNIEnv *, jclass);

/*
 * Class:     org_SocioNet_ServerRunner
 * Method:    writeGroupsToFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_SocioNet_ServerRunner_writeGroupsToFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
